### PR TITLE
add docker file and scripts update

### PR DESCRIPTION
**Pull request by ychenbioinfo**
Hi, 

I've created a dockerfile for msg project. The container is based on ubuntu:16.04 which has better compatible with some of the source codes. I also updated several scripts so msg doesn't need to be linked under the data folder, which would be convenient for docker run. 

The container can be created using 'docker build -f "Dockerfile" -t msg:latest .' . I also push the container to the docker hub, so you can pull it directly using 'docker pull ychenbioinfo/msg' and use the command 'docker run -v <local data folder>:/data ychenbioinfo/msg:latest msgCluster.pl' to run data analysis. 

The container has been tested and successfully finished msg.run1 and 2. It failed in the latter step, might because I don't have enough RAM. 

Please let me know if you have any questions.  My email is ychenbioinfo@gmail.com. 

Best,
Alvin

### CODE REVIEW

**Comment by YourePrettyGood** [comment]
Hi Alvin,
Thanks a ton for getting this container set up!

You're probably correct that msgRun3 failed due to insufficient RAM, msgRun3 is a major memory hog (and I recently added the plot_lod_matrix option to mitigate that problem, set to 0 to drastically reduce memory usage by skipping one diagnostic plot).

I'll try to get some test runs in within the next few days using existing data to make sure everything is working as intended, and will squash and merge when everything looks good!

Side note: I'm kind of tempted to adjust the image to use newer versions of some of the dependencies, since the dependency versions in the old README are substantially older than what we've been regularly using for years now.  In particular, bwa and zlib, but also just eliminating the pre-packaged Pyrex and installing from conda.
Any idea (from the Docker perspective) if this would introduce problems?

Best regards,
Patrick Reilly

**Comment by YourePrettyGood** [comment]
Alright, an update on this:
As mentioned in our e-mail exchanges, I had to fix a small bug in msgRun3 (i.e. `summaryPlots.R`), and make a few changes to the Dockerfile, but it looks like the image builds and runs the toy example properly.

I'm updating the `example_results` folder for `example_MSG_toy` to account for minor variations in the final matrices of posterior probabilities (the `ancestry-prob-par*.tsv` files) due to version changes of BWA.  I should have caught this several years ago, since we've been using BWA 0.7.12-r1044 on the Princeton clusters for years.  The matrices currently in the `example_results` folder come from BWA 0.5.7, and they change slightly using 0.5.9 (addition or removal of 6 AIMs out of about 4000), and again using 0.6.2, and then stabilize in the 0.7.x version range (plus or minus some bugs with some versions, e.g. 0.7.4).  I didn't see anything obvious in the `NEWS.md` of BWA to explain this, but the differences are so minor that they don't seem worth investigating.

I'll add a couple different Dockerfiles based on your original: One that uses bwa 0.5.7 as provided in the dependencies folder since that was particularly difficult to get working, and a second that uses bwa 0.7.17-0 via conda.

Beyond that, I have a couple other test datasets to run, but I'll do the merge before those are done.  The merge should happen sometime later tonight.

Thanks again for all your help!

**Comment by ychenbioinfo** [comment]
Hi Patrick, 

Thanks for the update. How was the testing work? I didn’t see the pull request has been merged, so I am wondering if there is anything wrong?

Best,
Alvin

**Comment by YourePrettyGood** [comment]
Hi Alvin,
Sorry for the confusion, I'm not great with git, so performed the merge on the command line and as far as I can tell it didn't register your commits in the commit history -- is this a side effect of the squash performed in commit dbcb77b?

The changes you made here, plus some additional changes I had to make for dependencies, have been merged into the dev branch in commit 0f520c2 .  The revised Docker image is available from Docker Hub under youreprettygood/msg:0.5 and I've noted that in the README in commit d016dbc

(The larger tests on other real datasets are in the works, but I'm satisfied with a thoroughly-troubleshooted toy example for now.)

Would it be advisable to close this PR here on Github?  Or is there a way to get the interface to recognize that your commits were included?

Thanks,
Patrick Reilly

**Comment by ychenbioinfo** [comment]
Hi Patrick, 

I think you've updated the code before the merge, so it created conflicts between mine and your updates. I've resolved all conflicts. There should be a button on your side to approve/merge the pull requests. Please check here for details: https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/merging-a-pull-request

Best,
Alvin

**Comment by YourePrettyGood** [comment]
Hi Alvin,
Thanks for taking care of that!  Sorry, I was following the command line merge instructions but must have deviated in some way to lead to this...

Welp, this has been a good learning experience!  Thanks for being so patient in helping me out!

Best regards,
Patrick Reilly

**Comment by ychenbioinfo** [comment]
No problem, Patrick. I am glad to help.

**Pull request merged**
